"""fk match

Revision ID: 3aca67ef5d95
Revises: b13358e3cf0b
Create Date: 2022-11-24 22:11:40.865037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aca67ef5d95'
down_revision = 'b13358e3cf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_id_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tournament_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'team', ['team_id_1'], ['id'])
        batch_op.create_foreign_key(None, 'tournament', ['tournament_id'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['team_id_2'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('team_team_id_1_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_team_id_2_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_tournament_id_fkey', type_='foreignkey')
        batch_op.drop_column('team_id_1')
        batch_op.drop_column('team_id_2')
        batch_op.drop_column('tournament_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team_id_2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team_id_1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('team_tournament_id_fkey', 'tournament', ['tournament_id'], ['id'])
        batch_op.create_foreign_key('team_team_id_2_fkey', 'team', ['team_id_2'], ['id'])
        batch_op.create_foreign_key('team_team_id_1_fkey', 'team', ['team_id_1'], ['id'])

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tournament_id')
        batch_op.drop_column('team_id_2')
        batch_op.drop_column('team_id_1')

    # ### end Alembic commands ###
