"""empty message

Revision ID: 625eebcea006
Revises: 31ecb2b508b0
Create Date: 2022-11-27 19:59:42.756375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625eebcea006'
down_revision = '31ecb2b508b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('round_number')

    # ### end Alembic commands ###
