"""add confirmation to tournament in db

Revision ID: 97df144eaa3b
Revises: b74484193fee
Create Date: 2022-11-25 23:24:41.725883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97df144eaa3b'
down_revision = 'b74484193fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('confirmation')

    # ### end Alembic commands ###
