"""empty message

Revision ID: b98f0469122e
Revises: 625eebcea006
Create Date: 2022-11-27 21:56:37.730144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98f0469122e'
down_revision = '625eebcea006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('team2_name', sa.String(length=150), nullable=True))
        batch_op.drop_constraint('match_team2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('match_team1_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team2_name'], ['name'])
        batch_op.create_foreign_key(None, 'team', ['team1_name'], ['name'])
        batch_op.drop_column('team2_id')
        batch_op.drop_column('team1_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team2_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('match_team1_id_fkey', 'team', ['team1_id'], ['id'])
        batch_op.create_foreign_key('match_team2_id_fkey', 'team', ['team2_id'], ['id'])
        batch_op.drop_column('team2_name')
        batch_op.drop_column('team1_name')

    # ### end Alembic commands ###
